# Generated by Django 5.2 on 2025-05-07 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('coordenadas', models.JSONField()),
                ('tem_agua_encanada', models.BooleanField()),
                ('tem_energia', models.BooleanField()),
                ('tipo_esgoto', models.CharField(choices=[('RP', 'Rede Pública'), ('FS', 'Fossa'), ('NN', 'Nenhum')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Domicílios',
            },
        ),
        migrations.CreateModel(
            name='Entrevistador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('area_cobertura', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('sincronizada', models.BooleanField(default=False)),
                ('domicilio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='censo.domicilio')),
                ('entrevistador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='censo.entrevistador')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1)),
                ('raca_cor', models.CharField(choices=[('B', 'Branca'), ('P', 'Preta'), ('PA', 'Parda'), ('I', 'Indígena'), ('A', 'Amarela')], max_length=2)),
                ('escolaridade', models.CharField(max_length=50)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='censo.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('entrevistas', models.ManyToManyField(to='censo.entrevista')),
            ],
        ),
    ]
